### ISSUE TITLE
Sprint #1

### ISSUE THREAD

**Issue by DionKasumi** [ferideberisha/nextgen_impactmakers#53]
Start working on below Use Cases (create, define and divide tasks)
- [ ] User has access on Home Page #57
- [ ]  #58

### **All Team:**
- [x] Finish Use Case Diagram
- [x] Extract working items from use case tickets
- [x] **first finish the use cases marked to this Sprint

**UI/UX**
- [x] Customize Our Services #54
- [x] Research for background texture #55
- [x] Create categories for Events, Trainings, Volunteering, and Internships #56

**Front End**
- [x] https://github.com/ferideberisha/nextgen_impactmakers/issues/60
- [x] https://github.com/ferideberisha/nextgen_impactmakers/issues/64
- [x] https://github.com/ferideberisha/nextgen_impactmakers/issues/66

**Back End**
- [x] https://github.com/ferideberisha/nextgen_impactmakers/issues/62
- [x] https://github.com/ferideberisha/nextgen_impactmakers/issues/61
- [x] https://github.com/ferideberisha/nextgen_impactmakers/issues/52
