### ISSUE TITLE
Create Signup Process

### ISSUE THREAD

**Issue by Qendresa-Potoku** [ferideberisha/nextgen_impactmakers#62]
### Create Signup Process

- [x] Implement a signup API for both **participants** and **organizations**.

#### Tasks:
1. **Participant Signup**:
   - [x] Required fields: `username`, `email`, `phone`, `password`.
   - [x] Validate input and call `add_participant()`.

2. **Organization Signup**:
   - [x] Required fields: `name_of_org`, `email_of_org`, `phone_number_of_org`, `password_of_org`, `url_of_org`, `description_of_org`.
   - [x] Validate input and call `add_organization()`.

3. **Debugging**:
  - [x] Log incoming data for debugging purposes.

4. **Error Handling**:
   - [x] Return a **400 error** for missing required fields.
