### ISSUE TITLE
Admin Panel

### ISSUE THREAD

**Issue by FestinaAvdiu** [ferideberisha/nextgen_impactmakers#73]
> BackEnd Tasks: 

- [ ] #79

      - Create an Admin URL 
      - Create a table in database for the Pre-Defined Admin Info (username & password will be pre-defined) 
      - Create an interface for LogIn Page for the Admin. The required fields: username & password, must match with the pre-defined ones in the database
      - Create an interface for Admin Panel, which will have a sidebar as a menu of 3 options:

**Option 1. Manage Users** 

- [ ] Admin can approve organizations #74

_An idea:_ 
_- We can create a temporary table to store the credentials of Organizations that sign up and we don't have them confirmed yet from the admin. Then, when the Admin approves the Organization, those credentials from the temporary table will be moved to the permanent one, and the Organization will get access to the website._

- [ ] Admin can check & change user account info #75

-  For Organization: It can change all the fields
-  For Participants: It can change all the fields

- [ ] Admin can ban or delete participant, in case of inappropriate username/behavior #76

**Option 2. Manage Cards**

- [ ] Admin can check & change card info, in case of request, error from the app, etc. #77

**Option 3. Manage Reviews/Feedback**

- [ ] Admin can delete reviews, only in case of inappropriate behavior #78
