### ISSUE TITLE
BackEnd: General Task

### ISSUE THREAD

**Issue by FestinaAvdiu** [ferideberisha/nextgen_impactmakers#95]
**BackEnd Tasks:**

- [x] Create a Model for the Database #99
- [x] Store User Preferences from Sign Up #97
- [x] Create Log In session for users #98
- [x] Scrape Contact Info & Update FrontEnd #108

**Meeting takeaways:** 

- Discuss if we should keep the check at Log In Form; if we'll remove it; or if we'll preselect Participant as default value
- Discuss what to show for Testimonials if missing; if we'll remove that section or if we'll show "Visit Source for more info" or "No testimonials given yet."
- Should Username be changeable on profile check? If yes, we need to add unique username check

**From last sprint:**

Continue with Admin Panel tasks - Refer back to #73 for further details

- [x] Check & Change Account Info #75 

- [x] Ban/Delete Participant #76 

- [x] Check & Change Card Info #77 

- [x] Manage Reviews #78 (Waiting for User Profiles)
